In [3]:
import numpy as np

In [4]:
array = np.ones(9)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
# Createing a 1d array

a = np.array([2,3,4,5,6])

print(a)

# Creating a 2d array

b = np.array([[1,2,3,4], [5,6,7,8]])
print(b)


[2 3 4 5 6]
[[1 2 3 4]
 [5 6 7 8]]


In [9]:
# Getting the dimension of the array
print(a.ndim)
print(b.ndim)


1
2


In [10]:
# Getting the shape of numpy arrays
print(a.shape)
print(b.shape) # returns (2 rows, 4 colms)

(5,)
(2, 4)


In [11]:
# Getting the datatype of the array in numpy

print(a.dtype) # int32

int32


In [12]:
# Specifing the datatype in a numpy array

c = np.array([2, 3,4,5,6,8,9], dtype='int16')

# getting the datatype of numpy array c

print(c.dtype) # int16

int16


In [13]:
# Getting the size of the array

# int32 type
print(a.itemsize) # 4
# the int16 type
print(c.itemsize) # 2


4
2


In [15]:
#  Getting the total number of elements in the array

print(b
    .size)

8


In [16]:
## Getting the total size of an array

## ------------ METHOD 1
print(a.itemsize * a.size)
##------------- METHOD 2
print(a.nbytes)


20
20


In [22]:
npArray = np.array([[5, 10, 15, 20, 25, 30], [2, 4,6, 8, 10, 12]])
# The shape
print(npArray.shape)

# The number of elements
print(npArray.size)

# The total memory in an array
print(npArray.size * npArray.itemsize)
# OR
print(npArray.nbytes)


# GETTING THE ELEMENT 10 IN OUR ARRAY

print(npArray[1, -2])
# OR
print(npArray[1, 4])

# GETTING A SPECIFIC ROW
print(npArray[1, :])
# OR 
print(npArray[-1: :][0])

# GETTING A SPECIFIC COLUMN (last column)
print(npArray[:, -1])
print(npArray[:, 5])


(2, 6)
12
48
48
10
10
[ 2  4  6  8 10 12]
[ 2  4  6  8 10 12]
[30 12]
[30 12]


In [26]:
### Numpy array indexing using `array[index, startindex, endindex, step]`

# Let's say we want to get all the numbers that ends with 5

print(npArray[0, 0: -1: 2])



[ 5 15 25]


In [40]:
## Changing the item value in an array `array[index, index] = value`

# Let's say we ant to update 10 in the npArray to be 100

npArray[1, -2] = 100
print(npArray[1,-2]) # 100

# Let's say now we want to change all the numbers that ends with 5 to have a value of 99
npArray[0, 0: -1:2] = 99

npArray

100


array([[ 99,  10,  99,  20,  99,  30],
       [  2,   4,   6,   8, 100,  12]])

In [53]:

# 3 Dimensional Array

np3D = np.array([
    [
        [2,4,6,8,10],
        [4,8,12,16,20]
    ],
    [
        [3,6,9, 12, 15],
        [6,12,18, 24, 30]
    ]
])

#  Getting the dimension

print(np3D.ndim) # 3

# Getting the total elements
print(np3D.size) # 20

# Getting the total memory
print(np3D.nbytes) # 80

# Getting the element 18 from the array
print(np3D[-1,-1, -3]) # 18



3
20
80
18


In [65]:
## Initializing Different types of arrays

### np.zeros(shape, type)
zeros = np.zeros([2, 4, 6])
zeros
print(zeros.dtype)

### np.ones(shape, type)
ones = np.ones((2, 3,5), dtype=np.uint32)
ones

### any number 255

whiteImage = np.full((4,4), 255, dtype='uint32')
whiteImage

### full_like
# Let's say we want to generate the array of 100s that has the same shape with whiteImage array

array100s = np.full_like(whiteImage, 9)
array100s


float64


array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]], dtype=uint32)

In [75]:
# generating an array of decimals

randomFloat = np.random.rand(2,3,6)
randomFloat

# Generating an array of integers
randomInt = np.random.randint(-7, 15, size=(7, 9,7))
randomInt


array([[[ 6,  0, 14,  0,  7, 10, 12],
        [ 7,  1,  7, -3, -7, -5,  3],
        [ 3, 12,  9, -4,  7, -6,  2],
        [-6, 12,  5, -5, 13,  3, 13],
        [-4,  6,  2, 14, -3,  4,  2],
        [ 1, 12,  7, -1,  7,  6,  6],
        [ 8, 14,  2, -6,  5, 10, -5],
        [10,  2, 11, -6, -2,  7, -2],
        [ 6, -7,  0, -1, -2,  0, 14]],

       [[ 2,  4,  3, -3,  8,  9, -6],
        [10, 11, -1, -5,  3,  7, 10],
        [ 8, -7, 14, 13,  3, 13, 13],
        [13, 10, 14,  1, 12,  6, -3],
        [10,  9, -1,  5,  3,  4,  1],
        [ 4, -1, -6,  6, -5,  3,  2],
        [10,  3, -6,  0,  6,  1, 11],
        [-7, -6,  6,  7, -6, -3,  8],
        [ 9,  6, 14, -7, -2, 12, -7]],

       [[ 8,  3, -3,  7, -7, 10, 10],
        [ 8, -4, -6,  9, -5, 14,  2],
        [ 5,  8,  5, -6, -5,  2,  7],
        [13, -7, 12,  1,  0, 13, -3],
        [-6, 12,  5, -7,  9, 14, -1],
        [-6, 10, -3, -5,  3, -1, 14],
        [-1, 14,  0, -5, -6,  2,  1],
        [12,  4,  7, 11,  0, 11, -1],
        

In [78]:
# np.identity(number, dtype)
# Generates the identity matrix
identity = np.identity(4, dtype='int8')
identity


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [80]:
# Repeating an array

arr1 = np.array([[2,4,6]])
arr2 = np.repeat(arr1, 3, axis=0) #  repeates vertically
arr2

arr3 = np.repeat(arr1, 3, axis=1) # Repeats horizontally
arr3

array([[2, 2, 2, 4, 4, 4, 6, 6, 6]])

In [84]:
## Copying arrays

array1 = np.array([1,2,3,4,5])
array2 = array1
print(array2) # [1 2 3 4 5]
array2[-1]= 500
print(array2) # [1 2 3 4 500]
# Array1 also changes 
print(array1) # [1 2 3 4 500]


##-------------------------

array1 = np.array([1,2,3,4,5])
array2 = array1.copy()
print(array2) # [1 2 3 4 5]
array2[-1]= 500
print(array2) # [1 2 3 4 500]
# Array1 also changes 
print(array1) # [1 2 3 4 5]



[1 2 3 4 5]
[  1   2   3   4 500]
[  1   2   3   4 500]
[1 2 3 4 5]
[  1   2   3   4 500]
[1 2 3 4 5]


In [91]:

a = np.array([2,3,4,5,9,90])



### Trigonometry
print(np.sin(a))
print(np.cos(a))
print(np.tan(a)) 
#  There are more

### Maths on two arrays
b = np.array([1,2,3,4,5,6])
print(a * b)
print(a ** b)
print(a / b)
print(a - b)
print(a + b)
# There are more

### Math on one array
print(a * b)
print(a ** b)
print(a / b)
print(a - b)
print(a + b)
# There are more


[ 0.90929743  0.14112001 -0.7568025  -0.95892427  0.41211849  0.89399666]
[-0.41614684 -0.9899925  -0.65364362  0.28366219 -0.91113026 -0.44807362]
[-2.18503986 -0.14254654  1.15782128 -3.38051501 -0.45231566 -1.99520041]
[  2   6  12  20  45 540]
[          2           9          64         625       59049 -1134944704]
[ 2.          1.5         1.33333333  1.25        1.8        15.        ]
[ 1  1  1  1  4 84]
[ 3  5  7  9 14 96]
[  2   6  12  20  45 540]
[          2           9          64         625       59049 -1134944704]
[ 2.          1.5         1.33333333  1.25        1.8        15.        ]
[ 1  1  1  1  4 84]
[ 3  5  7  9 14 96]


In [95]:
# Linear Algebra

a = np.ones([2, 2], dtype='int32')
b = np.full([2,2], 3, dtype= 'int32')

print(a * b) 
# The correct way
print(np.matmul(a, b))


## Getting the deteminant of a
print(np.linalg.det(b))


[[3 3]
 [3 3]]
[[6 6]
 [6 6]]
0.0


In [98]:
# Statistics with numpy

arr = np.array([[2, 3, 4, 5,-1,9],[100, 19, 100, 78,10,-90]])

print(np.max(arr))

print(np.min(arr))

print(np.sum(arr))

100
-90
239


In [106]:
# Reshaping arrays

arr = np.array([[2, 3, 4,5],[100, 19, 100, 7]])
print(arr.shape) # (2,4)

arr2 = arr.reshape([1, 8])
print(arr2.shape) # (1, 8)





(2, 4)
(1, 8)


array([[  2,   3,   4,   5, 100,  19, 100,   7]])

In [108]:
## Stacking arrays

## Vertical stack of arrays or matrixes
arr1 = np.array([2,3,4,5,8])
arr2 = np.array([1,2,3,4,5])

print(np.vstack([arr1, arr2]))

# Horizontal stacking of arrays or matrixes

arr1 = np.array([2,3,4,5,8])
arr2 = np.array([1,2,3,4,5])

print(np.hstack([arr1, arr2]))


[[2 3 4 5 8]
 [1 2 3 4 5]]
[2 3 4 5 8 1 2 3 4 5]


In [116]:
# Generating arrays from a file

## Suppose we have a file that has list of numbers seperated by a comma and we want to read this file and into a numpy array

# with default dtype
data = np.genfromtxt('data.txt', delimiter=',')
data

# As integer datatype

data = np.genfromtxt('data.txt', delimiter=',', dtype='int32')
data
#  Or 
data.astype('int8')



array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]], dtype=int8)

In [120]:
# Advanced indexing and Boolean Masking

data = np.genfromtxt('data.txt', delimiter=',', dtype='int32')

data[data%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79])

In [126]:
#Indexing return elements that are at index, `1, 2, 6, 9` and the last element in the array `data` where elements are `ODD`

data = np.genfromtxt('data.txt', delimiter=',', dtype='int32')
data[data%2==1][[1, 2, 6, 9, -1]]





array([ 3,  5, 13, 19, 79])