### Numpy

In this notebook we are going to learn how to work and manipulate `ndarrays` using numpy.

<p align="center"><img width="200" src="numpy.png" alt="img"/></p>

We are going to learn the following:

* array creation ✅
* input and output ✅
* array datatypes and shapes ✅
* array manipulations
* binary operations
* string operations
* date time functions
* linear algebra
* statistics
* sorting searching and counting.


### 1. Array Creation

* In this section we are going to learn how to create and initialize arrays in numpy. First things first we need to import our `numpy` package with an alias `np`. 

In [1]:
import numpy as np

Let's check the verison of `numpy` that we are using.

In [2]:
np.__version__

'1.24.3'

Creating an array using the `empty` function. Note that the `empty` function accept the shape of the array to be created.

In [3]:
array = np.empty(shape=(2, 4))
array

array([[0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 7.41e-321, 0.00e+000, 0.00e+000]])

We can also create an `empty` array with the shape of the existing array using the `empty_like` function as follows:

In [4]:
arr1 = np.array([[2, 4], [4, 7]])
array = np.empty_like(arr1)
array

array([[  920960341, -1402901369],
       [-1921571376, -1087293442]])

We can create an array or `0s` and `1s` using the `eye`.

> The `eye` return a 2-D array with `ones` on the diagonal and `zeros` elsewhere.


In [5]:
array = np.eye(4)
array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

One of the usecase of the `eye` function is to  create `one_hot_encoding` vectors by using the active index of a class. Let's implement a function that will create a one_hot vectors for our classes (red, green, blue) 

In [6]:
classes = "red, green, blue".split(', ')
def one_hot(index: int):
    return np.eye(len(classes))[index]

# blue
one_hot(2)

array([0., 0., 1.])

We can also create arrays with `1s` on the main diagonal using the `identity` function.

In [7]:
array = np.identity(4)
array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

We can create a `one_hot` encoding funstion using this numpy `identity` function as follows

In [8]:
def one_hot(index: int):
    return np.identity(len(classes))[index]
# red
one_hot(0)

array([1., 0., 0.])

We can create array of `1s` using the `ones` or `ones_like` in numpy as follows:

In [9]:
ones = np.ones(shape=(2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
ones = np.ones_like(array)
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

We can also create array of `zeros` using the `zeros` and `zeros_like` function in numpy as follows:

In [11]:
zeros = np.zeros(shape=(2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
zeros = np.zeros_like(ones)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In numpy we only create array with `zeros` and `ones` using `zeros` or `ones` function. Let's say we want to create an array with `4s` in it, how can we do that? 

> With the help of `full` and `full_like` we can create an array of numbers filled with a specified digit.

In [13]:
fours = np.full(shape=(2, 3), fill_value=4 )
fours

array([[4, 4, 4],
       [4, 4, 4]])

In [14]:
fours = np.full_like(zeros, fill_value=4 )
fours

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

We are not limited to create an array using the `full` method of just numbers, we can create array of any type for example in the following code cell we are going to create a `2x3` array with the boolean value `True`.

In [15]:
np.full(shape=(2, 3), fill_value=True )

array([[ True,  True,  True],
       [ True,  True,  True]])

We can create arrays using the `array` method. This method is very flexible in creating arrays as it allows us to create arrays with our own values without bothering in specifying the shape of the array.

> Note that the values in this array must have the same datatype. 

In [16]:
array = np.array([2, 3, 4, 5])
array

array([2, 3, 4, 5])

In [17]:
array = np.array([[2, 3, 4], [5, 6, 7.]])
array

array([[2., 3., 4.],
       [5., 6., 7.]])

In [18]:
array = np.array([True, False, True, True, False])
array

array([ True, False,  True,  True, False])

We can create array from a file. Suppose we have a file that has the following contents in it:
    
```
12 15 -17 8 7 89 77
13 14 -17 8 7 89 77
```
And the file name is `numbers.txt` we can load these numbers in a numpy array using a `fromfile` numpy function as follows

In [19]:
array = np.fromfile('numbers.txt', sep=' ')
array

array([ 12.,  15., -17.,   8.,   7.,  89.,  77.,  13.,  14., -17.,   8.,
         7.,  89.,  77.])

The good thing with numpy is that we can also generate arrays from iteratables using the `fromiter`. The following is an example that generates array from an iteratable object.

In [20]:
numbers = iter(range(0, 10 , 2))
array = np.fromiter(numbers, dtype=np.int32)
array

array([0, 2, 4, 6, 8])

In [21]:
numbers = (x for x in range(0, 11, 2))
array = np.fromiter(numbers, dtype=np.int32)
array

array([ 0,  2,  4,  6,  8, 10])

We can generate array fro  strings using the `fromstring` function. In the following code cell we are going to generate array of number from a string as follows:

In [22]:
numbers = '12 15 -17 8 7 89 77'
array = np.fromstring(numbers, sep=' ')
array

array([ 12.,  15., -17.,   8.,   7.,  89.,  77.])

In numpy we can generate array of numbers using the `arange` fuction. We need to specify the start, stop and the step.

In [23]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a = np.arange(start=0, stop=-10, step=-2)
a

array([ 0, -2, -4, -6, -8])

### Input and Output

In this section we are going to learn how we can save and load numpy arrays to static file. The first method that we are going to learn is the `save`.

The `np.save()` method allows us to save numpy arrays as a binary file with an extension `.npy`. In the forllowing example we are going to create a huge array that we are going to save as a binary file.



In [25]:
filename = 'myarray.npy'
array = np.random.rand(4, 4, 7)

In [26]:
np.save(filename, array)
print("Saved")

Saved


In [27]:
array[0][0]

array([0.2481371 , 0.26389222, 0.45320085, 0.34242893, 0.79846798,
       0.03733755, 0.83885017])

Now that we have saved our array in a binary file, we can load this file as an array using the `load` method.

In [28]:
my_array = np.load(filename)

In [29]:
my_array[0][0]

array([0.2481371 , 0.26389222, 0.45320085, 0.34242893, 0.79846798,
       0.03733755, 0.83885017])

We can also save our numpy arrays as `text` files using the `savetxt` method. For exmple let's save our array to a text file. **But `savetxt` only saves arrays that are in `2D` whilist `np.save()` allows us to save arrays that are in any dimension as arrays are saved in a binary file.**.

In [30]:
array = np.random.rand(100, 100)

np.savetxt('myarray.txt', array)
print("Saved!!")

Saved!!


In [31]:
array[0][:3]

array([0.69577801, 0.10102957, 0.13332387])

With the `savetxt()` numpy function we can save arrays with an extenstion `.gz` this will allows us to save automatically in compressed `gzip` format. Let's try to save our array in `.gz` format.

In [32]:
np.savetxt('myarray.gz', array)
print("Saved!!")

Saved!!


We can load these arrays from a `.txt` file using the `loadtxt` method as follows:

In [33]:
a = np.loadtxt('myarray.txt')
a[0][:3]

array([0.69577801, 0.10102957, 0.13332387])

We can also load the `.gz` format file in an array using the `loadtxt()` method as it understands `gzipped` files transparently.

In [34]:
a = np.loadtxt('myarray.gz')
a[0][:3]

array([0.69577801, 0.10102957, 0.13332387])

### Array Datatypes and Shapes

The first thing that we need to understand is that numpy arrays have shape and datatypes. In this section we are going to create different arrays with diffen shapes and datatypes. Let's create an array of  numbers.


In [35]:
array1 = np.array([1, 2, 5, -8, 7, 9])
array2 = np.array([1, 2, 5, -8, 7, 9.])
array3 = np.array([True, False, True])
array4 = np.array(["True", "False", "True"])
array5 = np.array(['c', 'a', 'r'])
array6 = np.array([4j, 3j])


We can check the datatype that is used in an aray using the `.dtype`

In [36]:
array1.dtype

dtype('int32')

In [37]:
array2.dtype

dtype('float64')

In [38]:
array3.dtype

dtype('bool')

In [39]:
array4.dtype

dtype('<U5')

In [40]:
array5.dtype

dtype('<U1')

In [41]:
array6.dtype

dtype('complex128')

Casting datatypes in numpy can be done using the `astype` method. Types for numbers are as follows:

1. floats

* `float16`
* `float32`
* `float64`

2. integers
* `int8`
* `int16`
* `int32`
* `int64`
* `uint8`
* `uint16`
* `uint32`
* `uint64`

> Datatypes can be pased as a string ('float32') or you can pass them as `np.float32`

In [42]:
a = array1.astype('float32') 
a.dtype, a

(dtype('float32'), array([ 1.,  2.,  5., -8.,  7.,  9.], dtype=float32))

In [43]:
a = array1.astype(np.bool_)
a

array([ True,  True,  True,  True,  True,  True])

In [44]:
a = array1.astype(np.float16)
a

array([ 1.,  2.,  5., -8.,  7.,  9.], dtype=float16)

You can specify the datatype while creating an array.

In [45]:
b = np.arange(10, dtype=np.float16)
b, b.dtype

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16),
 dtype('float16'))

You can change the datatype using the array method `astype()` after creating an array as follows:

In [46]:
b = np.arange(10).astype('float16')
b, b.dtype

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16),
 dtype('float16'))

In this section of the notebook we are going to have a look at working with array shapes in numpy.

In [47]:
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8.]
])
array

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

We can check the shape of an array by calling the `.shape` property on an array as follows:

In [48]:
array.shape

(2, 4)

In [50]:
b.shape

(10,)

We can check the total number of elements in an array by calling the `.size` property in an array as folloqs

In [51]:
array.size

8

In [52]:
b.size

10

### Array Manupulation

In this section we are going to have a look at how we can manipulate arrays in numpy. We are going to have a look at:

1. reshaping arrays

* reshaping an array means that we are changing the shape of an array from one shape to another. To reshape an array we use the method called `reshape()`
    

In [57]:
b.reshape(5, 2)

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]], dtype=float16)

> Using a `-1` on the second or any dimension you are telling numpy that decide for me the remaining dim for an array. Example:

In [58]:
b.reshape(2, -1)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]], dtype=float16)

In [65]:
np.arange(100).reshape(2, 5, 10)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

`transpose()` method is used to change or switch dimensions of an array. Let's create a new array `c`.

In [66]:
c = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8.]
])
c

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [67]:
c.shape

(2, 4)

There are two ways of transposing array in numpy. using the property `T` on an array or using the `np.transpose()` function.

In [70]:
t = c.T
t

array([[1., 5.],
       [2., 6.],
       [3., 7.],
       [4., 8.]])

In [71]:
t.shape

(4, 2)

In [73]:
t = np.transpose(c)
t.shape

(4, 2)

In array manipulation we have a method called `flatten` which allows us to flatten an array.

In [75]:
t.flatten()

array([1., 5., 2., 6., 3., 7., 4., 8.])

You can specify the direction in which you want your array to be `flattened` by default it's `C`

In [79]:
t.flatten(order='A') # order = {‘C’, ‘F’, ‘A’, ‘K’}

array([1., 2., 3., 4., 5., 6., 7., 8.])

We have a method that removes axes of length one from an array called `squeeze()`.

In [97]:
x = np.array([[[0], [1], [2]]])
print(x.shape)

np.squeeze(x).shape

(1, 3, 1)


(3,)

In [83]:
b.squeeze()

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)

We have a method called `expand_dims` that inserts a new axis that will appear at the axis position in the expanded array shape.

In [98]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)

In [102]:
np.expand_dims(b, axis=0)

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=float16)

### References

1. [numpy.org](https://numpy.org/doc/stable/reference/routines.html#)